name: "checkin' out"
description: "check out source code"
inputs:
  path:
    description: "Where to check out source code"
    required: false
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        path: ${{ inputs.path }}
    - run: ls -al ${{ inputs.path }}
