name: "checkin' out"
inputs:
  path:
    description: 'Where to check out source code'
    required: false
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - uses: actions/checkout@v2
      with:
        path: ${{ inputs.path }}
    - run: ls -al ${{ inputs.path }}
