  on: [workflow_dispatch]
  
  jobs:
    checkout:
      runs-on: ubuntu-latest
      steps:
      - uses: ./composite@main
      - uses: ./composite@main
        with:
          path: some-subdirectory
