  on: [workflow_dispatch, push]
  
  jobs:
    checkout:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: .github/actions/composite_action
      - uses: ./composite
      - uses: ./composite
        with:
          path: some-subdirectory
